---  
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8010/eureka/
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/,http://eureka-primary:8011/eureka/    
      
---
spring:
  profiles: adjective
wordConfig:  
  words: reasonable,leaky,suspicious,ordinary,unlikely
